title: Studio
subtitle: "Education and IDEs for everyone!"
description: "Status Studio is a Integrated Developer Environment and Education Platform that addresses pain points in the community with goal to grow the Ethereum ecosystem and foster one-stop-shop development and learning."
author: Status Studio
language: en
timezone: UTC

url: https://status-im.github.io
root: /studio.status.im/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  branch: gh-pages
  name: status-im-auto
  repo: git@github.com:status-im/incubate.status.im.git

theme_config:
    favicon: img/logo-32.png

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
twitter: ethstatus
github: staus-im
